# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slop-v3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slop-v3.proto',
  package='voldemort',
  syntax='proto3',
  serialized_pb=_b('\n\rslop-v3.proto\x12\tvoldemort\"f\n\x04Slop\x12\r\n\x05store\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x12\r\n\x05value\x18\x04 \x01(\x0c\x12\x0f\n\x07node_id\x18\x05 \x01(\x05\x12\x0f\n\x07\x61rrived\x18\x06 \x01(\x03\x42\'\n\x17voldemort.serializationB\nVSlopProtoH\x01\x62\x06proto3')
)




_SLOP = _descriptor.Descriptor(
  name='Slop',
  full_name='voldemort.Slop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='store', full_name='voldemort.Slop.store', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='voldemort.Slop.operation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='voldemort.Slop.key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='voldemort.Slop.value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='voldemort.Slop.node_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arrived', full_name='voldemort.Slop.arrived', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['Slop'] = _SLOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Slop = _reflection.GeneratedProtocolMessageType('Slop', (_message.Message,), dict(
  DESCRIPTOR = _SLOP,
  __module__ = 'slop_v3_pb2'
  # @@protoc_insertion_point(class_scope:voldemort.Slop)
  ))
_sym_db.RegisterMessage(Slop)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027voldemort.serializationB\nVSlopProtoH\001'))
# @@protoc_insertion_point(module_scope)
